// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQDG2-3Xvi-CYvsWUFLLwfWP-7IQRcxq4',
    appId: '1:844535779764:web:72bb1b87e3be11898362e1',
    messagingSenderId: '844535779764',
    projectId: 'invest-30ee1',
    authDomain: 'invest-30ee1.firebaseapp.com',
    storageBucket: 'invest-30ee1.appspot.com',
    measurementId: 'G-CYMRTPB0ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMt4vIObaNnGTMB9DOlCAS0RfCMDwaTTM',
    appId: '1:844535779764:android:5d8039022b47a6698362e1',
    messagingSenderId: '844535779764',
    projectId: 'invest-30ee1',
    storageBucket: 'invest-30ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL0oa7JZ9EZe0SYTYBGi1fVnPUTmyOroQ',
    appId: '1:844535779764:ios:11c38001e30a27428362e1',
    messagingSenderId: '844535779764',
    projectId: 'invest-30ee1',
    storageBucket: 'invest-30ee1.appspot.com',
    iosClientId: '844535779764-irkkimbdrmnr79pup6ur5vrs15mcppl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.invest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL0oa7JZ9EZe0SYTYBGi1fVnPUTmyOroQ',
    appId: '1:844535779764:ios:11c38001e30a27428362e1',
    messagingSenderId: '844535779764',
    projectId: 'invest-30ee1',
    storageBucket: 'invest-30ee1.appspot.com',
    iosClientId: '844535779764-irkkimbdrmnr79pup6ur5vrs15mcppl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.invest',
  );
}
